name: Python application

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FLASK_ENV: testing
      FLASK_APP: app.py
      FLASK_DEBUG: 1
      FLASK_APP_DATABASE_URL: "sqlite:///:memory":
      SQLALCHEMY_DATABASE_URI: "sqlite:///:memory":
      PYTHONPATH: ${{ github.workspace }}
      WEATHER_APP_API_KEY: your_dummy_api_key_for_testing

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up database
      run: |
        python -c "from app import app, weather_db; app.app_context().push(); weather_db.create_all()"
        flask db upgrade

    - name: Test with pytest
      run: |
        python -m pytest